import { NextResponse } from 'next/server';
import { getSessionAndPermissions } from '@/lib/auth';

export const dynamic = 'force-dynamic';

function hasPerm(user, slug) {
  if (user.role === 'super_admin') return true;
  const pages = Array.isArray(user.allowedPages) ? user.allowedPages : [];
  return pages.includes('*') || pages.includes(slug);
}

function fmt(val, decimals = 2) {
  if (val == null) return '';
  return Number(val).toFixed(decimals);
}

function pct(val) {
  if (val == null) return '';
  return Number(val).toFixed(2) + '%';
}

// GET /api/pnl/export?format=excel|csv&startDate=...&endDate=...
export async function GET(request) {
  const auth = await getSessionAndPermissions('pnl-export');
  if (!auth.success) {
    return NextResponse.json({ success: false, error: auth.error }, { status: auth.status || 403 });
  }
  const user = auth.user;
  const canViewCosts = hasPerm(user, 'pnl-costs');

  const { searchParams } = new URL(request.url);
  const format     = searchParams.get('format')     || 'csv';
  const startDate  = searchParams.get('startDate')  || '';
  const endDate    = searchParams.get('endDate')     || '';
  const detailLevel= searchParams.get('detailLevel')|| 'category';

  // Forward the full query string to the data API (server-side call)
  const dataUrl = new URL('/api/pnl/data', `http://localhost`);
  searchParams.forEach((v, k) => { if (k !== 'format') dataUrl.searchParams.set(k, v); });
  dataUrl.searchParams.set('pageSize', '9999'); // get all for export

  // Re-use the cookie for the internal call
  const cookieHeader = request.headers.get('cookie') || '';

  let reportData;
  try {
    const res = await fetch(dataUrl.toString().replace('http://localhost', process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'), {
      headers: { cookie: cookieHeader },
      cache:   'no-store',
    });
    reportData = await res.json();
  } catch (e) {
    return NextResponse.json({ success: false, error: 'Failed to fetch report data: ' + e.message }, { status: 500 });
  }

  if (!reportData?.success) {
    return NextResponse.json({ success: false, error: reportData?.error || 'Data fetch failed' }, { status: 500 });
  }

  const { summary, categories } = reportData;

  if (format === 'csv') {
    // ── CSV Export ─────────────────────────────────────────────────────────────
    const rows = [];

    // Header info
    rows.push(['HCC Product Category Profit & Loss']);
    rows.push(['Report Range:', `${startDate} to ${endDate}`]);
    rows.push(['Generated:', new Date().toLocaleString()]);
    rows.push(['Generated by:', user.name || user.email]);
    rows.push(['']);

    // Summary
    rows.push(['EXECUTIVE SUMMARY']);
    rows.push(['Gross Sales', fmt(summary.grossSales)]);
    rows.push(['Discounts',   fmt(summary.discounts)]);
    rows.push(['Refunds',     fmt(summary.refunds)]);
    rows.push(['Net Sales',   fmt(summary.netSales)]);
    if (canViewCosts) {
      rows.push(['COGS',         fmt(summary.cogs)]);
      rows.push(['Gross Profit', fmt(summary.grossProfit)]);
      rows.push(['Gross Margin', pct(summary.grossMargin)]);
    }
    rows.push(['Taxes',       fmt(summary.taxes)]);
    rows.push(['Net Qty Sold',fmt(summary.netQty, 0)]);
    rows.push(['Invoice Count', summary.invoiceCount]);
    rows.push(['']);

    // Category table header
    const catHeaders = [
      'Product Category', 'Parent Category',
      'Qty Sold', 'Qty Returned', 'Net Qty',
      'Gross Sales', 'Discounts', 'Refunds', 'Net Sales',
    ];
    if (canViewCosts) catHeaders.push('COGS', 'Gross Profit', 'Gross Margin %');
    catHeaders.push('Taxes', 'Invoice Count', '% of Total Sales');
    if (canViewCosts) catHeaders.push('% of Total Profit');
    rows.push(catHeaders);

    for (const cat of categories) {
      const row = [
        cat.catName, cat.parentCatName || '',
        fmt(cat.qtySold, 0), fmt(cat.qtyReturned, 0), fmt(cat.netQty, 0),
        fmt(cat.grossSales), fmt(cat.discounts), fmt(cat.refunds), fmt(cat.netSales),
      ];
      if (canViewCosts) {
        row.push(fmt(cat.cogs), fmt(cat.grossProfit), pct(cat.grossMargin));
      }
      row.push(fmt(cat.taxes), cat.invoiceCount, pct(cat.pctOfTotalSales));
      if (canViewCosts) row.push(pct(cat.pctOfTotalProfit));
      rows.push(row);

      // Product-level rows if detail includes products
      if ((detailLevel === 'product' || detailLevel === 'full') && cat.products) {
        for (const prod of cat.products) {
          const prodRow = [
            `  ↳ ${prod.productName} [${prod.sku || 'N/A'}]`, '',
            fmt(prod.qtySold, 0), fmt(prod.qtyReturned, 0), fmt(prod.netQty, 0),
            fmt(prod.grossSales), fmt(prod.discounts), fmt(prod.refunds), fmt(prod.netSales),
          ];
          if (canViewCosts) {
            prodRow.push(fmt(prod.cogs), fmt(prod.grossProfit), pct(prod.grossMargin));
          }
          prodRow.push(fmt(prod.taxes), prod.invoiceCount, '');
          if (canViewCosts) prodRow.push('');
          rows.push(prodRow);
        }
      }
    }

    // Grand total
    const totalRow = [
      'GRAND TOTAL', '',
      fmt(summary.netQty + (summary.invoiceCount ? 0 : 0), 0), '', fmt(summary.netQty, 0),
      fmt(summary.grossSales), fmt(summary.discounts), fmt(summary.refunds), fmt(summary.netSales),
    ];
    if (canViewCosts) {
      totalRow.push(fmt(summary.cogs), fmt(summary.grossProfit), pct(summary.grossMargin));
    }
    totalRow.push(fmt(summary.taxes), summary.invoiceCount, '100.00%');
    if (canViewCosts) totalRow.push('100.00%');
    rows.push(totalRow);

    // Convert to CSV string
    const csv = rows.map(row =>
      row.map(cell => {
        const s = String(cell ?? '');
        return s.includes(',') || s.includes('"') || s.includes('\n')
          ? `"${s.replace(/"/g, '""')}"`
          : s;
      }).join(',')
    ).join('\r\n');

    const filename = buildFilename(startDate, endDate, categories, 'csv');

    return new NextResponse(csv, {
      status: 200,
      headers: {
        'Content-Type':        'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  }

  if (format === 'excel') {
    // ── Excel Export via xlsx ──────────────────────────────────────────────────
    // Dynamic import xlsx (already in dependencies)
    const XLSX = await import('xlsx');

    const wb = XLSX.utils.book_new();

    // Sheet 1: Executive Summary
    const summaryData = [
      ['HCC Product Category Profit & Loss', ''],
      ['Report Range', `${startDate} to ${endDate}`],
      ['Generated', new Date().toLocaleString()],
      ['Generated by', user.name || user.email],
      ['', ''],
      ['Metric', 'Value'],
      ['Gross Sales',   fmt(summary.grossSales)],
      ['Discounts',    fmt(summary.discounts)],
      ['Refunds',      fmt(summary.refunds)],
      ['Net Sales',    fmt(summary.netSales)],
      ...(canViewCosts ? [
        ['COGS',         fmt(summary.cogs)],
        ['Gross Profit', fmt(summary.grossProfit)],
        ['Gross Margin', pct(summary.grossMargin)],
      ] : []),
      ['Taxes',        fmt(summary.taxes)],
      ['Net Qty Sold', fmt(summary.netQty, 0)],
      ['Invoice Count',String(summary.invoiceCount)],
    ];
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

    // Sheet 2: Category P&L
    const catHeaders = [
      'Product Category', 'Parent Category',
      'Qty Sold', 'Qty Returned', 'Net Qty',
      'Gross Sales', 'Discounts', 'Refunds', 'Net Sales',
    ];
    if (canViewCosts) catHeaders.push('COGS', 'Gross Profit', 'Gross Margin %');
    catHeaders.push('Taxes', 'Invoice Count', '% of Total Sales');
    if (canViewCosts) catHeaders.push('% of Total Profit');

    const catRows = [catHeaders];
    for (const cat of categories) {
      const row = [
        cat.catName, cat.parentCatName || '',
        cat.qtySold, cat.qtyReturned, cat.netQty,
        cat.grossSales, cat.discounts, cat.refunds, cat.netSales,
      ];
      if (canViewCosts) row.push(cat.cogs, cat.grossProfit, cat.grossMargin != null ? cat.grossMargin / 100 : '');
      row.push(cat.taxes, cat.invoiceCount, cat.pctOfTotalSales != null ? cat.pctOfTotalSales / 100 : '');
      if (canViewCosts) row.push(cat.pctOfTotalProfit != null ? cat.pctOfTotalProfit / 100 : '');
      catRows.push(row);
    }
    // Grand total
    const grandRow = ['GRAND TOTAL', '', summary.qtySold || '', summary.qtyReturned || '', summary.netQty, summary.grossSales, summary.discounts, summary.refunds, summary.netSales];
    if (canViewCosts) grandRow.push(summary.cogs, summary.grossProfit, summary.grossMargin != null ? summary.grossMargin / 100 : '');
    grandRow.push(summary.taxes, summary.invoiceCount, 1);
    if (canViewCosts) grandRow.push(1);
    catRows.push(grandRow);

    const wsCat = XLSX.utils.aoa_to_sheet(catRows);
    XLSX.utils.book_append_sheet(wb, wsCat, 'Category P&L');

    // Sheet 3: Product Detail (if requested and permitted)
    if ((detailLevel === 'product' || detailLevel === 'full') && categories.some(c => c.products)) {
      const prodHeaders = [
        'Category', 'Product Name', 'SKU',
        'Qty Sold', 'Qty Returned', 'Net Qty',
        'Avg Selling Price', 'Gross Sales', 'Discounts', 'Refunds', 'Net Sales',
      ];
      if (canViewCosts) prodHeaders.push('Avg Unit Cost', 'COGS', 'Gross Profit', 'Gross Margin %');
      prodHeaders.push('Taxes', 'Invoice Count', 'Current Cost Flag');

      const prodRows = [prodHeaders];
      for (const cat of categories) {
        for (const prod of (cat.products || [])) {
          const row = [
            cat.catName, prod.productName, prod.sku || '',
            prod.qtySold, prod.qtyReturned, prod.netQty,
            prod.avgSellingPrice, prod.grossSales, prod.discounts, prod.refunds, prod.netSales,
          ];
          if (canViewCosts) {
            row.push(prod.avgUnitCost, prod.cogs, prod.grossProfit, prod.grossMargin != null ? prod.grossMargin / 100 : '');
          }
          row.push(prod.taxes, prod.invoiceCount, prod.currentCostFlag ? 'Current Cost' : '');
          prodRows.push(row);
        }
      }
      const wsProd = XLSX.utils.aoa_to_sheet(prodRows);
      XLSX.utils.book_append_sheet(wb, wsProd, 'Product Detail');
    }

    // Sheet 4: Invoice Lines (full detail if requested and permitted)
    if (detailLevel === 'full') {
      const invHeaders = [
        'Category', 'Product', 'Invoice Date', 'Invoice Number',
        'Customer', 'Qty', 'Unit Price', 'Discount %', 'Net Revenue',
      ];
      if (canViewCosts) invHeaders.push('Unit Cost', 'Line COGS', 'Gross Profit');
      invHeaders.push('Salesperson', 'Payment Status', 'Type');

      const invRows = [invHeaders];
      for (const cat of categories) {
        for (const prod of (cat.products || [])) {
          for (const line of (prod.invoiceLines || [])) {
            const row = [
              cat.catName, prod.productName,
              line.invoiceDate, line.invoiceNumber,
              line.customer, line.qty, line.unitPrice, line.discount, line.netRevenue,
            ];
            if (canViewCosts) row.push(line.unitCost, line.lineCogs, line.grossProfit);
            row.push(line.salesperson, line.paymentStatus, line.isCreditNote ? 'Credit Note' : 'Invoice');
            invRows.push(row);
          }
        }
      }
      const wsInv = XLSX.utils.aoa_to_sheet(invRows);
      XLSX.utils.book_append_sheet(wb, wsInv, 'Invoice Lines');
    }

    // Sheet 5: Filter Info
    const filterData = [
      ['Filter', 'Value'],
      ['Start Date', startDate],
      ['End Date', endDate],
      ['Detail Level', detailLevel],
      ['Generated At', new Date().toLocaleString()],
      ['Generated By', user.name || user.email],
      ['Accounting Basis', searchParams.get('basis') || 'accrual'],
    ];
    const wsFilters = XLSX.utils.aoa_to_sheet(filterData);
    XLSX.utils.book_append_sheet(wb, wsFilters, 'Report Info');

    const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    const filename = buildFilename(startDate, endDate, categories, 'xlsx');

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type':        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  }

  return NextResponse.json({ success: false, error: 'Invalid format. Use excel or csv.' }, { status: 400 });
}

function buildFilename(startDate, endDate, categories, ext) {
  const s = (startDate || 'start').replace(/-/g, '-');
  const e = (endDate   || 'end').replace(/-/g, '-');
  // If only one category in the filter, include its name
  const singleCat = categories?.length === 1
    ? '_' + (categories[0].catName || '').replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').slice(0, 30)
    : '';
  return `HCC_PNL${singleCat}_${s}_to_${e}.${ext}`;
}
